### ISSUE TITLE
Repo sync failure

### ISSUE THREAD

**Issue by MinorThreat1** [sonyxperiadev/local_manifests#101]
branch android-8.0.0_r30
vendor-nxp and transpower are missing o-mr1 branch. Can I use p-mr1 branch instead?

Error messages:
Fetching projects:  32% (186/575) platform/packages/apps/CellBroadcastReceiverfatal: couldn't find remote ref refs/heads/o-mr1
vendor-nxp:
fatal: couldn't find remote ref refs/heads/o-mr1

Fetching projects:  45% (264/575) platform/packages/apps/Car/Overviewerror: Cannot fetch transpower from https://github.com/sonyxperiadev/transpower

Fetching projects:  49% (285/575) platform/packages/providers/DownloadProvidererror: Cannot fetch vendor-nxp from https://github.com/sonyxperiadev/vendor-nxp

Checking out projects:  97% (560/574) vendor-broadcom-wlanerror: Cannot checkout vendor-nxp: ManifestInvalidRevisionError: revision o-mr1 in vendor-nxp not found
error: in `sync`: revision o-mr1 in vendor-nxp not found

**Comment by Haxk20** [comment]
Hello. Please do not open issue here but open one at our bug_tracker.
[Here](https://github.com/sonyxperiadev/bug_tracker/issues)
Thank you.
Also please close this one.

**Comment by MinorThreat1** [comment]
Moved issue to bugtracker
