### ISSUE TITLE
d6633

### ISSUE THREAD

**Issue by mo421** [sonyxperiadev/local_manifests#105]
please,when i write lunch do not appear my Sony xperia d6633, how to solve this

**Comment by MartinX3** [comment]
Please open bugreports in https://github.com/sonyxperiadev/bug_tracker

Also please take a look here
https://developer.sony.com/develop/open-devices/get-started/supported-devices-and-functionality/

**Comment by mo421** [comment]
i'm not found what i want

‫في الأحد، 16 أغسطس 2020 في 3:44 م تمت كتابة ما يلي بواسطة ‪Martin
Dünkelmann‬‏ <‪notifications@github.com‬‏>:‬

**Comment by MartinX3** [comment]
Yes, the xperia Z3 is not supported anymore (legacy device).
You probably get luck if you try the Android 7.1.2 of SODP
https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-nougat-7-1-2

**Comment by mo421** [comment]
OK.. Many thanks
بتاريخ ١٧‏/٠٨‏/٢٠٢٠ ٣:٠٥ م، كتب "Martin Dünkelmann" <
notifications@github.com>:

**Comment by Haxk20** [comment]
@jerpelea Please close this
