### ISSUE TITLE
Can not build xperia 10 II ROM (android-11.0.0_r27)

### ISSUE THREAD

**Issue by egorovandreyrm** [sonyxperiadev/local_manifests#120]
`build/make/core/Makefile:49: error: overriding commands for target out/target/product/pdx201/vendor/etc/sensors/config/sns_device_orient_somc_platform.json, previously defined at build/make/core/base_rules.mk:492`

android-11.0.0_r29 is also not working.

If I fix the error by removing `sns_device_orient_somc_platform.json` from `/device/sony/pdx201/device.mk`, the ROM can be built and it boots but wifi and the cellular connection are not working.

Please advise.

**Comment by ix5** [comment]
Please use the [issue tracker](https://github.com/sonyxperiadev/bug_tracker/issues) so that we can collect issues in one place.

**Comment by jerpelea** [comment]
fixed
