### ISSUE TITLE
Repo sync has fatal error 

### ISSUE THREAD

**Issue by nikolowry** [sonyxperiadev/local_manifests#25]
Trying to build the latest, but am getting the following error after running `repo sync`:

```
fatal: remove-project element specifies non-existent project: platform/hardware/qcom/camera
```

After manually deleting https://github.com/sonyxperiadev/local_manifests/blob/fa76b2e9fdba728714b89ca9e145fab950aeb96d/LA.UM.6.4.r1.xml#L4, there is another `repo sync` fatal eror:

```
fatal: remove-project element specifies non-existent project: device/google/wahoo-kernel
```

After manually deleting https://github.com/sonyxperiadev/local_manifests/blob/fa76b2e9fdba728714b89ca9e145fab950aeb96d/untracked.xml#L8 `repo sync` finally starts syncing.

---

Don't know how confident I am in how this build will turn out though. I've successfully built M, N, O in the past, but these latest errors occurred when following the instructions at https://developer.sonymobile.com/open-devices/aosp-build-instructions/how-to-build-aosp-oreo-for-unlocked-xperia-devices/ for 8.0.0r30

Off-topic: Is there revision history of the page at https://developer.sonymobile.com/open-devices/aosp-build-instructions/how-to-build-aosp-oreo-for-unlocked-xperia-devices/?  If not, is there anyway you could tag the revisions here? I don't build often, and there's been some bad builds when a new major version is released -- so it be great to have some reference of all the build instructions' revisions

**Comment by jerpelea** [comment]
hi
please use the new build guides from
https://developer.sony.com/develop/open-devices/
you are getting errors because following the old guide you will use Android 8.0 with patches for Android 8.1

**Comment by nikolowry** [comment]
@jerpelea had no idea! It'd be helpful to put an alert notice about the new guide on developer.sonymobile.com.

Regardless, thanks for pointing me in the right direction

**Comment by eogut** [comment]
I got a similar error while trying to build Android Q r15.
First, I received:
```
fatal: remove-project element specifies non-existent project: platform/external/nos/host/android
```
Solved by removing the respective line from
https://github.com/sonyxperiadev/local_manifests/blob/2b12fa6d0d20ec166eff4bf376373bd32c109867/untracked.xml#L4

I got this error afterwards
```
fatal: remove-project element specifies non-existent project: platform/external/nos/test/system-test-harness
```
Solved by removing the respective line from
https://github.com/sonyxperiadev/local_manifests/blob/2b12fa6d0d20ec166eff4bf376373bd32c109867/untracked.xml#L6

I was using this guide: https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-android-android-10-0-0

**Comment by MarijnS95** [comment]
@eogut The build guide mentions in step 4 to checkout `local_manifests` on the same branch (`android-10.0.0_r15`) which [removes the offending lines](https://github.com/sonyxperiadev/local_manifests/commit/f8ba73195469459a487ecaf96be22aca0462539b). Did you perhaps miss a step?

**Comment by eogut** [comment]
@MarijnS95 I noticed that, too... So, checking again, while I put the 
branch under step 4.1, I haven't noticed the `<branch>` under step 4.2, so 
I just copied and pasted the whole code. It seems that in this case the 
cloning was done at master level. But I built an AOSP image this way that I 
didn't flash yet. So that build should be useless, right?

I suggest to add some hint to the guide under 4.2 as that remark for 
inserting the branch again can be overlooked.


Am 24. Dezember 2019 20:31:58 schrieb MarijnS95 <notifications@github.com>:

**Comment by MarijnS95** [comment]
> So that build should be useless, right?

The difference between that branch and master is really small. Just check it out, run `./repo_update.sh` again and build _without cleaning!_ These are really only minor incremental changes. For good measure, run `make installclean` to clean up only the packaging directories which makes sure now-unused files don't make it into the system.

> I suggest to add some hint to the guide under 4.2 as that remark for inserting the branch again can be overlooked.

Angle brackets are the "de facto standard" when it comes to pieces of text that need to be filled in by the user. Point to be made, these guides are to "guide" you through the build process (hopefully how and why to do a certain step) and not to be blindly copypasted. If it was, there would have been a shell script to do it instead. The segments of code to copy are really small, and the same `<branch>` replacement is in the correctly executed `repo init` as well.

**Comment by eogut** [comment]
Hi Marijn,

so I'll navigate into the AOSP folder, just run `./repo_update.sh` and 
start building? Or shall I run `make installclean` before starting the 
build process again?

And yes I know it's the de facto standard, I'm just saying maybe 
highlighting that bracket term in red or something would make it easier for 
novices like me to not overlook that field. :) I look at the code before 
inserting it, but being in the same colour it just slipped through... Just 
a suggestion, not really a negative criticism! :)

Thanks and merry Christmas :)

Am 25. Dezember 2019 15:25:35 schrieb MarijnS95 <notifications@github.com>:

**Comment by MarijnS95** [comment]
> so I'll navigate into the AOSP folder, just run `./repo_update.sh` and start building? Or shall I run `make installclean` before starting the build process again?

`repo_update.sh` does a `repo sync` and applies specific changes to the source repositories. `make installclean` on the other hand removes output files that would directly influence the images ending up in the build. In that way they are completely orthogonal and can be run in any order, as long as both are ran _before_ making the images again.

> highlighting that bracket term in red or something would make it easier for novices like me to not overlook that field.

It looks to me like their webpage editor automatically applies some kind of "syntax highlighting" to `<pre>` code blocks; not sure if this is possible but they might try...

Merry Christmas!
