### ISSUE TITLE
Error when try to build AOSP Pie 9.0

### ISSUE THREAD

**Issue by ChristianSchaefer** [sonyxperiadev/local_manifests#58]
I tried to build pie with the given build instruction from the sony aosp site.
Still now chance to get it working. I know there is a precompiled kernel for the pioneer, can i use this or is it not ready to work with pie?

> ============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
TARGET_PRODUCT=aosp_h4113
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a53
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=cortex-a53
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.15.0-34-generic-x86_64-Ubuntu-18.04.1-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PPR2.180905.005
OUT_DIR=out
============================================
[1/1] out/soong/.minibootstrap/minibp out/soong/.bootstrap/build.ninja
[55/56] glob libcore/openjdk_java_files.bp
[77/77] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
out/build-aosp_h4113-cleanspec.ninja is missing, regenerating...
out/build-aosp_h4113.ninja is missing, regenerating...
[119/947] including device/sony/common/Android.mk ...
hardware/qcom/media/sdm845/mm-video-v4l2/vidc/venc/Android.mk:45: warning: "venc: PQ compiled out"
rm: das Entfernen von 'out/target/product/pioneer/vendor/rfs/' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
/bin/bash: Zeile 0: pushd: out/target/product/pioneer/odm/: Datei oder Verzeichnis nicht gefunden
[562/947] including system/sepolicy/Android.mk ...
system/sepolicy/Android.mk:79: warning: BOARD_SEPOLICY_VERS not specified, assuming current platform version
[947/947] including vendor/qcom/opensource/wlan/wcnss-service/Android.mk ...
build/make/core/Makefile:71: warning: Duplicate header copy: out/target/product/pioneer/obj/include/qcom/display/qd_utils.h
build/make/core/Makefile:71: warning: Defined in: hardware/qcom/display/sde/libqdutils/../common.mk hardware/qcom/display/sde/libqdutils/../common.mk
build/make/core/Makefile:28: warning: overriding commands for target `out/target/product/pioneer/vendor/etc/gps.conf'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `out/target/product/pioneer/vendor/etc/gps.conf'
[ 99% 723/724] glob tools/tradefederation/core/python-lib/tradefed_py/*.py
ninja: error: 'kernel/sony/msm-4.9/common-kernel/kernel-dtb-pioneer', needed by 'out/target/product/pioneer/kernel', missing and no known rule to make it
15:09:23 ninja failed with: exit status 1

#### failed to build some targets (01:22 (mm:ss)) ####

**Comment by jerpelea** [comment]
Before the first vendor release we did not provide precompiled kernels and developers had to built them from source by running the kernel/sony/msm-4.9/common-kernel/build-kernels.sh script

As soon as we will release the vendor binaries for Android 9 we will also upload new kernel binaries

**Comment by MartinX3** [comment]
Please write it at
https://github.com/sonyxperiadev/bug_tracker
for instant help and close this issue.

And look at
https://github.com/sonyxperiadev/bug_tracker/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+NILE
