### ISSUE TITLE
Error Trying to build AOSP Pie 9.0 for F8332

### ISSUE THREAD

**Issue by cechetti** [sonyxperiadev/local_manifests#68]
This is a Make log

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
TARGET_PRODUCT=aosp_f8332
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=kryo
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=kryo
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.15.0-48-generic-x86_64-Ubuntu-18.04.2-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ2A.190405.003
OUT_DIR=out
============================================
renato@renato-Lenovo-IdeaPad-S400:~/android$ make -j 8
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
TARGET_PRODUCT=aosp_f8332
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=kryo
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=kryo
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.15.0-48-generic-x86_64-Ubuntu-18.04.2-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ2A.190405.003
OUT_DIR=out
============================================
ninja: no work to do.
[1/1] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja 
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -o out/soong/build.ninja Android.bp
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x897403, 0x16)
	prebuilts/go/linux-x86/src/runtime/panic.go:619 +0x81
runtime.sysMap(0xc4cc1c0000, 0x100000, 0x0, 0xb309f8)
	prebuilts/go/linux-x86/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0xb182c0, 0x100000, 0xc420051de8)
	prebuilts/go/linux-x86/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0xb182c0, 0x2, 0x0)
	prebuilts/go/linux-x86/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0xb182c0, 0x2, 0xb30a08, 0x442623)
	prebuilts/go/linux-x86/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0xb182c0, 0x2, 0xc420050049, 0x42633e)
	prebuilts/go/linux-x86/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
	prebuilts/go/linux-x86/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0xb182c0, 0x2, 0xffffffffff010049, 0x9)
	prebuilts/go/linux-x86/src/runtime/mheap.go:752 +0x8a
runtime.(*mcentral).grow(0xb1a850, 0x0)
	prebuilts/go/linux-x86/src/runtime/mcentral.go:232 +0x94
runtime.(*mcentral).cacheSpan(0xb1a850, 0x9)
	prebuilts/go/linux-x86/src/runtime/mcentral.go:106 +0x2e4
runtime.(*mcache).refill(0x7f45b6a976c8, 0xc420000d49)
	prebuilts/go/linux-x86/src/runtime/mcache.go:123 +0x9c
runtime.(*mcache).nextFree.func1()
	prebuilts/go/linux-x86/src/runtime/malloc.go:556 +0x32
runtime.systemstack(0x0)
	prebuilts/go/linux-x86/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
	prebuilts/go/linux-x86/src/runtime/proc.go:1170

goroutine 1 [running]:
runtime.systemstack_switch()
	prebuilts/go/linux-x86/src/runtime/asm_amd64.s:363 fp=0xc46caef390 sp=0xc46caef388 pc=0x455df0
runtime.(*mcache).nextFree(0x7f45b6a976c8, 0x749, 0x0, 0xc46caef430, 0x4440bf)
	prebuilts/go/linux-x86/src/runtime/malloc.go:555 +0xa9 fp=0xc46caef3e8 sp=0xc46caef390 pc=0x40fd89
runtime.mallocgc(0x700, 0x0, 0x0, 0xc4cc197800)
	prebuilts/go/linux-x86/src/runtime/malloc.go:710 +0x79f fp=0xc46caef488 sp=0xc46caef3e8 pc=0x4106df
runtime.rawstring(0x6bd, 0x0, 0x0, 0x0, 0x0, 0x0)
	prebuilts/go/linux-x86/src/runtime/string.go:245 +0x4f fp=0xc46caef4b8 sp=0xc46caef488 pc=0x4440bf
runtime.rawstringtmp(0x0, 0x6bd, 0x1, 0x6bc, 0xc4cc197800, 0x6bc, 0x6bc)
	prebuilts/go/linux-x86/src/runtime/string.go:115 +0x6f fp=0xc46caef4f8 sp=0xc46caef4b8 pc=0x443b1f
runtime.concatstrings(0x0, 0xc46caef5d8, 0x2, 0x2, 0xc48262a2a9, 0x1)
	prebuilts/go/linux-x86/src/runtime/string.go:46 +0x10a fp=0xc46caef590 sp=0xc46caef4f8 pc=0x44367a
runtime.concatstring2(0x0, 0xc4cc197800, 0x6bc, 0xc48262a2a9, 0x1, 0xc4cb53de60, 0x2a)
	prebuilts/go/linux-x86/src/runtime/string.go:55 +0x47 fp=0xc46caef5d0 sp=0xc46caef590 pc=0x443867
github.com/google/blueprint.(*ninjaString).ValueWithEscaper(0xc4831b76b0, 0xc4318bb830, 0xc4200744b0, 0x0, 0x0)
	/home/renato/android/build/blueprint/ninja_strings.go:283 +0xe7 fp=0xc46caef668 sp=0xc46caef5d0 pc=0x5a7027
github.com/google/blueprint.(*ninjaString).Value(0xc4831b76b0, 0xc4318bb830, 0x8896de, 0x6)
	/home/renato/android/build/blueprint/ninja_strings.go:274 +0x41 fp=0xc46caef6a0 sp=0xc46caef668 pc=0x5a6f11
github.com/google/blueprint.(*buildDef).WriteTo(0xc4831cc600, 0xc421efb100, 0xc4318bb830, 0x0, 0x0)
	/home/renato/android/build/blueprint/ninja_defs.go:391 +0x4e4 fp=0xc46caefa78 sp=0xc46caef6a0 pc=0x5a4f94
github.com/google/blueprint.(*Context).writeLocalBuildActions(0xc4201238c0, 0xc421efb100, 0xc438a67da8, 0x0, 0x0)
	/home/renato/android/build/blueprint/context.go:3418 +0x303 fp=0xc46caefb10 sp=0xc46caefa78 pc=0x59afc3
github.com/google/blueprint.(*Context).writeAllModuleActions(0xc4201238c0, 0xc421efb100, 0x0, 0x0)
	/home/renato/android/build/blueprint/context.go:3302 +0x869 fp=0xc46caefcc8 sp=0xc46caefb10 pc=0x59a3e9
github.com/google/blueprint.(*Context).WriteBuildFile(0xc4201238c0, 0x8f1b00, 0xc48128cbd0, 0x68b, 0xc439370000)
	/home/renato/android/build/blueprint/context.go:2970 +0x187 fp=0xc46caefd00 sp=0xc46caefcc8 pc=0x5977e7
github.com/google/blueprint/bootstrap.Main(0xc4201238c0, 0x883c20, 0xc420190000, 0xc4206d3f58, 0x3, 0x4)
	/home/renato/android/build/blueprint/bootstrap/command.go:171 +0x8e5 fp=0xc46caefec8 sp=0xc46caefd00 pc=0x60f4a5
main.main()
	/home/renato/android/build/soong/cmd/soong_build/main.go:75 +0x26d fp=0xc46caeff88 sp=0xc46caefec8 pc=0x7a36cd
runtime.main()
	prebuilts/go/linux-x86/src/runtime/proc.go:198 +0x212 fp=0xc46caeffe0 sp=0xc46caeff88 pc=0x42bc12
runtime.goexit()
	prebuilts/go/linux-x86/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc46caeffe8 sp=0xc46caeffe0 pc=0x4588f1
ninja: build stopped: subcommand failed.
02:42:49 soong bootstrap failed with: exit status 1

**Comment by jerpelea** [comment]
what CPU and how much memory do you have

**Comment by cechetti** [comment]
Hi, it's an old entry-level laptop: Intel Core i3 2365M; 4gb DDR3; 500gb. Better try a more powerful one?

**Comment by MartinX3** [comment]
at least 8gb ram, 16gb is recommended, 32gb would be the holy optimum (my experience)

**Comment by Vamp898** [comment]
I can verify that it builds fine for F8332 without any issues.
