### ISSUE TITLE
MODULE.TARGET.SHARED_LIBRARIES.libloc_core already defined by hardware/qcom/gps/sdm845/core when building 9.0.0_r46 for f8331

### ISSUE THREAD

**Issue by Vamp898** [sonyxperiadev/local_manifests#71]
root@igz-build-01:~/android# make -j64   
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
TARGET_PRODUCT=aosp_f8331
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=kryo
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=kryo
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.19.53-gentoo-op-x86_64-Debian-GNU/Linux-9-(stretch)
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ3A.190801.002
OUT_DIR=out
============================================
[1/1] out/soong/.minibootstrap/minibp out/soong/.bootstrap/build.ninja
[55/56] glob prebuilts/ndk/stl.bp
[77/77] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
out/build-aosp_f8331-cleanspec.ninja is missing, regenerating...
out/build-aosp_f8331.ninja is missing, regenerating...
[25/981] including development/build/Android.mk ...
development/build/build_android_stubs.mk:43: warning: android_stubs_current 
development/build/build_android_stubs.mk:43: warning: metalava_android_stubs_current metalava_android_stubs_current
development/build/build_android_stubs.mk:43: warning: android_system_stubs_current 
development/build/build_android_stubs.mk:43: warning: android_test_stubs_current 
development/build/build_android_stubs.mk:43: warning: metalava_android_system_stubs_current metalava_android_system_stubs_current
development/build/build_android_stubs.mk:43: warning: metalava_android_test_stubs_current metalava_android_test_stubs_current
[377/981] including hardware/qcom/gps/Android.mk ...
build/make/core/base_rules.mk:260: error: hardware/qcom/gps/msm8996/core: MODULE.TARGET.SHARED_LIBRARIES.libloc_core already defined by hardware/qcom/gps/sdm845/core.
06:29:42 ckati failed with: exit status 1

**Comment by jerpelea** [comment]
please run repo_update !

**Comment by Vamp898** [comment]
I did exactly that :o i did

make clobber

and re run the repo_update.sh script again, but same error :/

I will do a complete cleanup of the android directory and re-try again, if i do not come back, that helped.

Thank you very much for the fast response!
