### ISSUE TITLE
Prebuilts flex too old

### ISSUE THREAD

**Issue by maverick6664** [sonyxperiadev/local_manifests#72]
Hi,

I'm trying to build the latest android-9.0.0_r46 for h8266 on Fedora 30, but got an error like this:
`[ 10% 11128/106210] //external/selinux...policy lex policy_scan.l [linux_glibc]
FAILED: out/soong/.intermediates/external/selinux/checkpolicy/checkpolicy/linux_glibc_x86_64/gen/lex/external/selinux/checkpolicy/policy_scan.c 
prebuilts/misc/linux-x86/flex/flex-2.5.39 -oout/soong/.intermediates/external/selinux/checkpolicy/checkpolicy/linux_glibc_x86_64/gen/lex/external/selinux/checkpolicy/policy_scan.c external/selinux/checkpolicy/policy_scan.l
flex-2.5.39: loadlocale.c:130: _nl_intern_locale_data: Assertion cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
[ 10% 11137/106210] //art/tools/cpp-de...tor-data clang++ main.cc [linux_glibc]
ninja: build stopped: subcommand failed.
19:55:24 ninja failed with: exit status 1`

Apparently flex is doing wrong.   So I symlinked flex-2.5.39 to my /usr/bin/flex and resumed to make, it went smoothly.

I wonder where the fix be??

Thanks in advance!

**Comment by jerpelea** [comment]
builds fine on ubuntu

**Comment by maverick6664** [comment]
> Unfortunately is impossible to support every OS flavour.
> It builds fine on ubuntu .

Which version?

**Comment by jerpelea** [comment]
I tested 16 and 18

**Comment by ix5** [comment]
Android's prebuilt `flex` seems to be incompatible with your distro's `glibc` version.
Had the same issue on Arch Linux, easiest is to set up a Ubuntu chroot to avoid similar issues.

**Comment by maverick6664** [comment]
I've already installed Ubuntu 18 in vbox on Fedora.  Thanks to shared file capability it must be pretty easy to download and compile.  While I was sleeping my pc has been downloading.  Downloading by Fedora and compiling by Ubuntu.   But it's early morning here.  Let me sleep more.....zzzz
