### ISSUE TITLE
Reverse f2bc4d5e1bfd7d4b48d373350b70dac49c70d2af

### ISSUE THREAD

**Issue by Orange-NX** [sonyxperiadev/local_manifests#76]
Clearly not working!

> tr@instance-1:~/android$ export ALLOW_MISSING_DEPENDENCIES=true
tr@instance-1:~/android$ make -j 10
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=10
TARGET_PRODUCT=aosp_h4113
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a53
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=cortex-a53
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.0.0-1017-gcp-x86_64-Ubuntu-19.04
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=QP1A.190711.019
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=device/sony/nile
============================================
Environment variable ALLOW_MISSING_DEPENDENCIES was set, regenerating...
[  0% 2/432] including out/soong/Android-aosp_h4113.mk ...
[  0% 3/432] including art/Android.mk ...
[ 23% 103/432] including device/sony/common/Android.mk ...
IDisplayConfig version: DISPLAY_CONFIG_1_8
[ 52% 228/432] including hardware/qcom/sdm845/Android.mk ...
FAILED: 
hardware/qcom/power/Android.mk:2: error: hardware/qcom/sdm845/Android.mk: No such file or directory
15:12:34 ckati failed with: exit status 1

**Comment by jerpelea** [comment]
repo_update and it will work :)

**Comment by Orange-NX** [comment]
Also kernel for pioneer not builded!

**Comment by MartinX3** [comment]
Please use the gcc kernel build script before building android. :)

**Comment by Orange-NX** [comment]
Yes but it only build 4 devices at end not others

**Comment by Orange-NX** [comment]
here is my log 

` tompimousse2405@instance-1:~/android/kernel/sony/msm-4.14/common-kernel$ ./build-kernels-clang.sh
=================================================
Your Environment:
ANDROID_ROOT: /home/tompimousse2405/android
KERNEL_TOP  : /home/tompimousse2405/android/kernel/sony/msm-4.14
KERNEL_TMP  : /home/tompimousse2405/android/out/kernel-tmp
=================================================
Platform -> loire :: Device -> suzu
The build may take up to 10 minutes. Please be patient ...
Building new kernel image ...
Loggin to /home/tompimousse2405/android/out/kernel-tmp/build_log_suzu
Copying new kernel image ...
=================================================
Platform -> loire :: Device -> kugo
The build may take up to 10 minutes. Please be patient ...
Building new kernel image ...
Loggin to /home/tompimousse2405/android/out/kernel-tmp/build_log_kugo
Copying new kernel image ...
=================================================
Platform -> loire :: Device -> blanc
The build may take up to 10 minutes. Please be patient ...
Building new kernel image ...
Loggin to /home/tompimousse2405/android/out/kernel-tmp/build_log_blanc
Copying new kernel image ...
=================================================
Platform -> tone :: Device -> dora
The build may take up to 10 minutes. Please be patient ...
Building new kernel image ...
Loggin to /home/tompimousse2405/android/out/kernel-tmp/build_log_dora
Copying new kernel image ...
=================================================
Platform -> tone :: Device -> kagura
The build may take up to 10 minutes. Please be patient ...
Building new kernel image ...
Loggin to /home/tompimousse2405/android/out/kernel-tmp/build_log_kagura
Copying new kernel image ...
=================================================
Platform -> tone :: Device -> keyaki
The build may take up to 10 minutes. Please be patient ...
Building new kernel image ...
Loggin to /home/tompimousse2405/android/out/kernel-tmp/build_log_keyaki
Copying new kernel image ...
=================================================
Platform -> yoshino :: Device -> lilac
The build may take up to 10 minutes. Please be patient ...
Building new kernel image ...
Loggin to /home/tompimousse2405/android/out/kernel-tmp/build_log_lilac
Copying new kernel image ...
=================================================
Platform -> yoshino :: Device -> maple
The build may take up to 10 minutes. Please be patient ...
Building new kernel image ...
Loggin to /home/tompimousse2405/android/out/kernel-tmp/build_log_maple
Copying new kernel image ...
=================================================
Platform -> yoshino :: Device -> poplar
The build may take up to 10 minutes. Please be patient ...
Building new kernel image ...
Loggin to /home/tompimousse2405/android/out/kernel-tmp/build_log_poplar
Copying new kernel image ...
=================================================
Platform -> nile :: Device -> discovery
The build may take up to 10 minutes. Please be patient ...
Building new kernel image ...
Loggin to /home/tompimousse2405/android/out/kernel-tmp/build_log_discovery
Copying new kernel image ...
=================================================
Platform -> nile :: Device -> pioneer
The build may take up to 10 minutes. Please be patient ...
Building new kernel image ...
Loggin to /home/tompimousse2405/android/out/kernel-tmp/build_log_pioneer
Copying new kernel image ...
=================================================
Platform -> nile :: Device -> voyager
The build may take up to 10 minutes. Please be patient ...
Building new kernel image ...
Loggin to /home/tompimousse2405/android/out/kernel-tmp/build_log_voyager
Copying new kernel image ...
=================================================
Platform -> ganges :: Device -> kirin
The build may take up to 10 minutes. Please be patient ...
Building new kernel image ...
Loggin to /home/tompimousse2405/android/out/kernel-tmp/build_log_kirin
Copying new kernel image ...
=================================================
Platform -> ganges :: Device -> mermaid
The build may take up to 10 minutes. Please be patient ...
Building new kernel image ...
Loggin to /home/tompimousse2405/android/out/kernel-tmp/build_log_mermaid
Copying new kernel image ...
=================================================
Platform -> tama :: Device -> akari
The build may take up to 10 minutes. Please be patient ...
Building new kernel image ...
Loggin to /home/tompimousse2405/android/out/kernel-tmp/build_log_akari
Copying new kernel image ...
find: ‘/home/tompimousse2405/android/out/kernel-tmp/arch/arm64/boot/dts’: No such file or directory
create image file: /home/tompimousse2405/android/kernel/sony/msm-4.14/common-kernel/dtbo-akari.img...
Total 0 entries.
=================================================
Platform -> tama :: Device -> apollo
The build may take up to 10 minutes. Please be patient ...
Building new kernel image ...
Loggin to /home/tompimousse2405/android/out/kernel-tmp/build_log_apollo
Copying new kernel image ...
find: ‘/home/tompimousse2405/android/out/kernel-tmp/arch/arm64/boot/dts’: No such file or directory
create image file: /home/tompimousse2405/android/kernel/sony/msm-4.14/common-kernel/dtbo-apollo.img...
Total 0 entries.
=================================================
Platform -> tama :: Device -> akatsuki
The build may take up to 10 minutes. Please be patient ...
Building new kernel image ...
Loggin to /home/tompimousse2405/android/out/kernel-tmp/build_log_akatsuki
Copying new kernel image ...
find: ‘/home/tompimousse2405/android/out/kernel-tmp/arch/arm64/boot/dts’: No such file or directory
create image file: /home/tompimousse2405/android/kernel/sony/msm-4.14/common-kernel/dtbo-akatsuki.img...
Total 0 entries.
=================================================
Platform -> kumano :: Device -> griffin
The build may take up to 10 minutes. Please be patient ...
Building new kernel image ...
Loggin to /home/tompimousse2405/android/out/kernel-tmp/build_log_griffin
Copying new kernel image ...
find: ‘/home/tompimousse2405/android/out/kernel-tmp/arch/arm64/boot/dts’: No such file or directory
create image file: /home/tompimousse2405/android/kernel/sony/msm-4.14/common-kernel/dtbo-griffin.img...
Total 0 entries.
=================================================
Clean up environment
Done!
tompimousse2405@instance-1:~/android/kernel/sony/msm-4.14/common-kernel$  `

and output

` tompimousse2405@instance-1:~/android/kernel/sony/msm-4.14/common-kernel$ ls
KernelConfig.mk  build-kernels-clang.sh  build-kernels-gcc.sh  dtbo-akari.img  dtbo-akatsuki.img  dtbo-apollo.img  dtbo-griffin.img
tompimousse2405@instance-1:~/android/kernel/sony/msm-4.14/common-kernel$ `

**Comment by MartinX3** [comment]
`Loggin to /home/tompimousse2405/android/out/kernel-tmp/xxxx` as described in your sent logs.
There are the informations why your kernel build failed.

**Comment by Orange-NX** [comment]
Log isn't here...
probaly due to clean

**Comment by MartinX3** [comment]
Please only execute the bash script to build the kernels in a terminal window.
Then gather the generated log.

**Comment by Orange-NX** [comment]
I don't really understand 
I checked in kernel_tmp and there nothing in.

**Comment by Orange-NX** [comment]
I'm using ubuntu without gui

**Comment by ix5** [comment]
What are the contents of `/home/tompimousse2405/android/out/` ?

---

Please format your logs like using three backticks (```)
```
tompimousse2405@instance-1:~/android/kernel/sony/msm-4.14/common-kernel
$./build-kernels-clang.sh
Your Environment:
ANDROID_ROOT: /home/tompimousse2405/android
KERNEL_TOP : /home/tompimousse2405/android/kernel/sony/msm-4.14
KERNEL_TMP : /home/tompimousse2405/android/out/kernel-tmp
Platform -> loire :: Device -> suzu
The build may take up to 10 minutes. Please be patient ...
Building new kernel image ...
Loggin to /home/tompimousse2405/android/out/kernel-tmp/build_log_suzu
Copying new kernel image ...

[...]
```

**Comment by ix5** [comment]
Also please create bugs in https://github.com/sonyxperiadev/bug_tracker/issues in the future.
Anything related to Android 10 is still very much in alpha, you are expected to fix issues yourself.

**Comment by Orange-NX** [comment]
```  GNU nano 3.2                                                                                  build_log_pioneer                                                                                             
make[1]: Entering directory '/home/tompimousse2405/android/out/kernel-tmp'
  CHK     include/config/kernel.release
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     scripts/mod/devicetable-offsets.h
  LEX     scripts/dtc/dtc-lexer.lex.c
/bin/sh: 1: flex: not found
make[3]: *** [scripts/Makefile.lib:211: scripts/dtc/dtc-lexer.lex.c] Error 127
make[2]: *** [/home/tompimousse2405/android/kernel/sony/msm-4.14/kernel/scripts/Makefile.build:678: scripts/dtc] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/home/tompimousse2405/android/kernel/sony/msm-4.14/kernel/Makefile:579: scripts] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/tompimousse2405/android/out/kernel-tmp'
make: *** [Makefile:146: sub-make] Error 2
```
log of kernel build in android/out

**Comment by ix5** [comment]
`apt install flex`...

**Comment by Orange-NX** [comment]
I did remove rm in sh script

**Comment by Orange-NX** [comment]
seem working it's longer than before

**Comment by ix5** [comment]
Github isn't a chat. Please don't spam messages here. Investigate issues yourself and then report back with details of what you did, and logs.

**Comment by Orange-NX** [comment]
Thanks, you helped my mind kernel builded succefully!
